config/routes.rb
Alchemy::Engine.routes.draw do

  root :to => 'pages#show'

  get '/sitemap.xml' => 'pages#sitemap', format: 'xml'

  get '/admin' => redirect(
    "#{Alchemy::MountPoint.get}/admin/dashboard"
  )

  get '/admin/dashboard' => 'admin/dashboard#index',
        :as => :admin_dashboard
  get '/admin/dashboard/info' => 'admin/dashboard#info',
        :as => :dashboard_info
  get '/admin/help' => 'admin/dashboard#help',
        :as => :help
  get '/admin/dashboard/update_check' => 'admin/dashboard#update_check',
        :as => :update_check

  get '/attachment/:id/download(/:name)' => 'attachments#download',
        :as => :download_attachment
  get '/attachment/:id/show' => 'attachments#show',
        :as => :show_attachment

  # Picture urls
  get "/pictures/:id/show(/:size)(/:crop)(/:crop_from/:crop_size)(/:quality)/:name.:format" => 'pictures#show',
        :as => :show_picture
  get '/pictures/:id/zoom/:name.:format' => 'pictures#zoom',
        :as => :zoom_picture
  get "/pictures/:id/thumbnails/:size(/:crop)(/:crop_from/:crop_size)/:name.:format" => 'pictures#thumbnail',
        :as => :thumbnail, :defaults => {:format => 'png', :name => "thumbnail"}

  get '/admin/leave' => 'base#leave', :as => :leave_admin

  resources :messages, :only => [:index, :new, :create]
  resources :elements, :only => :show
  resources :contents, :only => :show

  namespace :admin do

    resources :contents do
      collection do
        post :order
      end
    end

    resources :pages do
      resources :elements
      collection do
        post :order
        post :flush
        post :copy_language_tree
        get :switch_language
        get :create_language
        get :link
        get :sort
      end
      member do
        post :unlock
        post :publish
        post :fold
        post :visit
        get :configure
        get :preview
        get :info
      end
    end

    resources :elements do
      resources :contents
      collection do
        get :list
        post :order
      end
      member do
        post :fold
        delete :trash
      end
    end

    resources :layoutpages, :only => [:index, :edit]

    resources :pictures do
      collection do
        post :flush, :update_multiple
        delete :delete_multiple
        get :edit_multiple
      end
      member do
        get :info
        delete :remove
      end
    end

    resources :attachments do
      member do
        get :download
      end
    end

    resources :essence_pictures, :except => [:show, :new, :create] do
      collection do
        put :assign
      end
      member do
        get :crop
      end
    end

    resources :essence_files, :only => [:edit, :update] do
      collection do
        put :assign
      end
    end

    resources :legacy_page_urls
    resources :languages

    resource :clipboard, :only => :index, :controller => 'clipboard' do
      collection do
        get :index
        delete :clear
        delete :remove
        post :insert
      end
    end

    resource :trash, :only => :index, :controller => 'trash' do
      collection do
        get :index
        delete :clear
      end
    end

    resources :tags do
      collection do
        get :autocomplete
      end
    end

    resources :sites

  end

  get '/:lang' => 'pages#show',
      :constraints => {:lang => /[a-z]{2}(-[a-z]{2})?/},
      :as => :show_language_root

  # The page show action has to be last route
  get '(/:lang)/*urlname(.:format)' => 'pages#show',
      :constraints => {:lang => /[a-z]{2}(-[a-z]{2})?/},
      :as => :show_page

end

app/models/alchemy/picture/sweeping.rb
module Alchemy
  module Picture::Sweeping
    extend ActiveSupport::Concern

    included do
      after_update  { expire_cache_for(self) }
      after_destroy { expire_cache_for(self) }
    end

    private

    # Removing all variants of the picture with FileUtils.
    def expire_cache_for(picture)
      FileUtils.rm_rf(Rails.root.join('public', Alchemy::MountPoint.get.gsub(/^\//, ''), 'pictures', picture.id.to_s))
    end
  end
end

app/controllers/alchemy/admin/pictures_controller.rb
module Alchemy
  module Admin
    class PicturesController < Alchemy::Admin::BaseController
      helper 'alchemy/admin/tags'

      respond_to :html, :js

      before_action :load_picture,
        only: [:show, :edit, :update, :info, :destroy]

      authorize_resource class: Alchemy::Picture

      def index
        @size = params[:size].present? ? params[:size] : 'medium'
        @pictures = Picture.all
        @pictures = @pictures.tagged_with(params[:tagged_with]) if params[:tagged_with].present?
        @pictures = @pictures.filtered_by(params[:filter]) if params[:filter]
        @pictures = @pictures.find_paginated(params, pictures_per_page_for_size(@size))
        if in_overlay?
          archive_overlay
        end
      end

      def new
        @picture = Picture.new
        set_size_or_default
        if in_overlay?
          set_instance_variables
        end
      end

      def create
        @picture = Picture.new(picture_params)
        @picture.name = @picture.humanized_name
        if @picture.save
          set_size_or_default
          if in_overlay?
            set_instance_variables
          end
          message = _t('Picture uploaded succesfully', name: @picture.name)
          render json: {files: [@picture.to_jq_upload], growl_message: message}, status: :created
        else
          message = _t('Picture validation error', name: @picture.name)
          render json: {files: [@picture.to_jq_upload], growl_message: message}, status: :unprocessable_entity
        end
      end

      def edit_multiple
        @pictures = Picture.where(id: params[:picture_ids])
        @tags = @pictures.collect(&:tag_list).flatten.uniq.join(', ')
      end

      def update
        if @picture.update_attributes(picture_params)
          flash[:notice] = _t(:picture_updated_successfully, name: @picture.name)
        else
          flash[:error] = _t(:picture_update_failed)
        end
        redirect_to_index
      end

      def update_multiple
        @pictures = Picture.find(params[:picture_ids])
        @pictures.each do |picture|
          picture.update_name_and_tag_list!(params)
        end
        flash[:notice] = _t("Pictures updated successfully")
        redirect_to_index
      end

      def delete_multiple
        if request.delete? && params[:picture_ids].present?
          pictures = Picture.find(params[:picture_ids])
          names = []
          not_deletable = []
          pictures.each do |picture|
            if picture.deletable?
              names << picture.name
              picture.destroy
            else
              not_deletable << picture.name
            end
          end
          if not_deletable.any?
            flash[:warn] = _t("These pictures could not be deleted, because they were in use", :names => not_deletable.to_sentence)
          else
            flash[:notice] = _t("Pictures deleted successfully", :names => names.to_sentence)
          end
        else
          flash[:warn] = _t("Could not delete Pictures")
        end
      rescue Exception => e
        flash[:error] = e.message
      ensure
        redirect_to_index
      end

      def destroy
        name = @picture.name
        @picture.destroy
        flash[:notice] = _t("Picture deleted successfully", :name => name)
      rescue Exception => e
        flash[:error] = e.message
      ensure
        do_redirect_to admin_pictures_path(:per_page => params[:per_page], :page => params[:page], :query => params[:query])
      end

      def flush
        FileUtils.rm_rf Rails.root.join('public', Alchemy::MountPoint.get, 'pictures')
        @notice = _t('Picture cache flushed')
      end

      private

      def load_picture
        @picture = Picture.find(params[:id])
      end

      def pictures_per_page_for_size(size)
        case size
        when 'small'
          per_page = in_overlay? ? 25 : (per_page_value_for_screen_size * 2.9).floor
        when 'large'
          per_page = in_overlay? ? 4 : (per_page_value_for_screen_size / 1.7).floor + 1
        else
          per_page = in_overlay? ? 9 : (per_page_value_for_screen_size / 1.0).ceil + 4
        end
        return per_page
      end

      def in_overlay?
        params[:element_id].present?
      end

      def archive_overlay
        @content = Content.select('id').find_by(id: params[:content_id])
        @element = Element.select('id').find_by(id: params[:element_id])
        @options = options_from_params
        respond_to do |format|
          format.html { render partial: 'archive_overlay' }
          format.js   { render action:  'archive_overlay' }
        end
      end

      def redirect_to_index
        redirect_to admin_pictures_path(
          query: params[:query],
          tagged_with: params[:tagged_with],
          size: params[:size],
          filter: params[:filter]
        )
      end

      def picture_params
        params.require(:picture).permit(:image_file, :upload_hash, :name, :tag_list)
      end

      def set_size_or_default
        @size = params[:size] || 'medium'
      end

      def set_instance_variables
        @while_assigning = true
        @content = Content.select('id').find_by(id: params[:content_id])
        @element = Element.select('id').find_by(id: params[:element_id])
        @options = options_from_params
        @page = params[:page] || 1
        @per_page = pictures_per_page_for_size(@size)
      end

    end
  end
end

app/controllers/alchemy/pictures_controller.rb
module Alchemy
  class PicturesController < Alchemy::BaseController
    ALLOWED_IMAGE_TYPES = %w(png jpeg gif)

    caches_page :show, :thumbnail, :zoom

    before_filter :ensure_secure_params

    load_and_authorize_resource

    def show
      @size = params[:size]
      expires_in 1.month, public: !@picture.restricted?
      respond_to { |format| send_image(processed_image, format) }
    end

    def thumbnail
      case params[:size]
        when 'small'  then @size = '80x60'
        when 'medium' then @size = '160x120'
        when 'large'  then @size = '240x180'
        when nil      then @size = '111x93'
      else
        @size = params[:size]
      end

      respond_to { |format| send_image(processed_image, format) }
    end

    def zoom
      image_file = @picture.image_file
      respond_to { |format| send_image(image_file, format) }
    end

    private

    def ensure_secure_params
      token = params[:sh]
      digest = PictureAttributes.secure(params)
      bad_request unless token && (token == digest)
    end

    def bad_request
      render text: "Bad picture parameters in #{request.path}", status: 400
      return false
    end

    def send_image(image, format)
      ALLOWED_IMAGE_TYPES.each do |type|
        format.send(type) do
          if type == 'jpeg'
            quality = params[:quality] || Config.get(:output_image_jpg_quality)
            image = image.encode(type, "-quality #{quality}")
          else
            image = image.encode(type)
          end
          render text: image.data
        end
      end
    end

    # Return the processed image dependent of size and cropping parameters
    def processed_image
      @image = @picture.image_file
      if @image.nil?
        raise MissingImageFileError, "Missing image file for #{@picture.inspect}"
      end
      if @size.present?
        if params[:crop_size].present? && params[:crop_from].present?
          @image = @image.thumb xy_crop_geometry_string(params)
          @image.thumb(resize_geometry_string)
        elsif params[:crop]
          @image.thumb(center_crop_geometry_string)
        else
          @image.thumb(resize_geometry_string)
        end
      else
        @image
      end
    end

    # Returns the Imagemagick geometry string for cropping the image.
    def xy_crop_geometry_string(params)
      crop_from_x, crop_from_y = params[:crop_from].split('x')
      "#{params[:crop_size]}+#{crop_from_x}+#{crop_from_y}"
    end

    # Returns the Imagemagick geometry string used to resize the image.
    #
    # Prevents upscaling unless :upsample param is true.
    def resize_geometry_string
      params[:upsample] == 'true' ? @size : "#{@size}>"
    end

    # Returns the Imagemagick geometry string used to crop the image.
    #
    # Prevents upscaling unless :upsample param is true
    def center_crop_geometry_string
      params[:upsample] == 'true' ? "#{@size}#" : "#{normalized_sizes(*@size.split('x'))}#"
    end

    # Ensure we're not trying to scale the image up. Used only for cropping.
    def normalized_sizes(width, height)
      if width.to_i > @image.width
        width = @image.width
      end
      if height.to_i > @image.height
        height = @image.height
      end
      "#{width}x#{height}"
    end
  end
end

app/helpers/alchemy/admin/pictures_helper.rb
module Alchemy
  module Admin
    module PicturesHelper

      def create_or_assign_url(picture_to_assign, options)
        if @content.nil?
          {
            :controller => :contents,
            :action => :create,
            :picture_id => picture_to_assign.id,
            :content => {
              :essence_type => "Alchemy::EssencePicture",
              :element_id => @element.id
            },
            :options => options
          }
        else
          {
            :controller => :essence_pictures,
            :action => :assign,
            :picture_id => picture_to_assign.id,
            :content_id => @content.id,
            :options => options
          }
        end
      end

    end
  end
end

app/views/alchemy/admin/pictures/_archive.html.erb
<div id="library_sidebar">
  <%= render :partial => 'filter_bar' %>
  <div id="tag_list" class="with_filter_bar<%= params[:tagged_with].present? ? ' filtered' : '' %>">
    <%= render :partial => 'tag_list' %>
  </div>
</div>
<%= form_tag delete_multiple_admin_pictures_path, :method => :delete do %>
  <div class="selected_item_tools">
    <h2><%= _t(:edit_selected_pictures) %></h2>
    <%= link_to(
      render_icon('edit') + _t("Edit"),
      edit_multiple_admin_pictures_path,
      :class => 'button with_icon',
      :title => _t('Edit multiple pictures'),
      :id => 'edit_multiple_pictures',
      :style => 'float: none'
    ) %>
    <%= button_tag render_icon('destroy') + _t("Delete"), 'data-alchemy-confirm' => {
      :title => _t(:please_confirm),
      :message => _t(:confirm_to_delete_images_from_server),
      :ok_label => _t("Yes"),
      :cancel_label => _t("No")
    }.to_json, :class => 'button with_icon' %>
    &nbsp;<%= _t(:or) %>&nbsp;
    <%= link_to(
      render_icon('delete-small') + _t("Clear selection"),
      admin_pictures_path(
        :query => params[:query],
        :tagged_with => params[:tagged_with],
        :size => params[:size],
        :filter => params[:filter]
      ),
      :class => 'button with_icon',
      :style => 'float: none'
    ) %>
  </div>
  <div id="pictures">
  <% if @pictures.blank? and @recent_pictures.blank? and params[:query].nil? %>
    <div class="info">
      <%= render_icon('info') %>
      <%= _t(:no_images_in_archive) %>
    </div>
  <% elsif @pictures.blank? and @recent_pictures.blank? %>
    <div class="info">
      <%= render_icon('info') %>
      <%= _t(:no_search_results) %>
    </div>
  <% else %>
    <%= render :partial => 'picture', :collection => @pictures %>
    <%= paginate @pictures, theme: 'alchemy' %>
  <% end %>
  </div>
<% end %>

app/views/alchemy/admin/pictures/_archive_overlay.html.erb
<div id="overlay_toolbar">
  <%= render 'filter_and_size_bar' %>
</div>
<div id="assign_image_list" class="with_padding<%= params[:tagged_with].present? ? ' filtered' : '' %>">
  <div id="library_sidebar">
    <%= render 'filter_bar' %>
    <div id="tag_list">
      <%= render 'tag_list' %>
    </div>
  </div>
  <div id="overlay_picture_list">
    <%= render 'overlay_picture_list' %>
  </div>
</div>

app/views/alchemy/admin/pictures/_filter_bar.html.erb
<% params_to_keep = [:size, :tagged_with, :query, :element_id, :options, :content_id, :_] %>

<div id="filter_bar">
  <h2><%= _t('Filter') %></h2>
  <%= select_tag(
    'picture_filter',
    options_for_select([
      [_t(:all_pictures), ''],
      [_t(:last_upload_only), 'last_upload'],
      [_t(:recently_uploaded_only), 'recent'],
      [_t(:without_tag), 'without_tag']
    ], params[:filter]),
    :data => { :remote => !!request.xhr? },
    :class => 'alchemy_selectbox'
  ) %>
</div>

<script type="text/javascript">
  $(function() {
    $('#picture_filter').on('change', function(e) {
      var $this = $(this);
      var url = '<%= alchemy.admin_pictures_path(merge_params_only(params_to_keep)).html_safe %>';
      if ($this.data('remote') === true) {
        $.get(url, {filter: $this.val()}, null, 'script');
      } else {
        Alchemy.pleaseWaitOverlay();
        delimiter = url.match(/\?/) ? '&' : '?';
        window.location = url + delimiter + 'filter=' + $this.val();
      }
      return false;
    });
  });
</script>

app/views/alchemy/admin/pictures/_overlay_picture_list.html.erb
<% if @pictures.empty? %>
  <div class="info">
    <%= render_icon('info') %>
    <%= _t(:no_images_in_archive) %>
  </div>
<% else %>
  <%= render partial: 'picture_to_assign',
    collection: @pictures,
    locals: {options: @options, size: @size} %>
  <%= paginate @pictures, theme: 'alchemy', remote: true %>
<% end %>

app/views/alchemy/admin/pictures/_picture_to_assign.html.erb
<div class="picture_thumbnail assign_image_list_detail <%= size.blank? ? 'medium' : size %>" name="<%= picture_to_assign.name %>" id="picture_to_assign_<%= picture_to_assign.id %>">
<% unless params[:image_assign_url].blank? %>
  <% action_url = params[:image_assign_url] + "?picture_id=#{picture_to_assign.id}" %>
  <% action_method = params[:image_assign_method] %>
<% else %>
  <% action_url = create_or_assign_url(picture_to_assign, @options.to_json) %>
  <% action_method = @content.blank? ? 'post' : 'put' %>
<% end %>
  <%= link_to(
    image_tag(
      alchemy.thumbnail_path(
        id: picture_to_assign,
        size: size,
        sh: picture_to_assign.security_token(size: size)
      ),
      alt: picture_to_assign.name
    ),
    action_url,
    remote: true,
    onclick: '$(self).attr("href", "#").off("click"); return false',
    method: action_method,
    title: _t(:assign_image),
    class: 'thumbnail_background'
  ) %>
  <div class="picture_name" title="<%= picture_to_assign.name %>">
    <%= picture_to_assign.name.empty? ? "&nbsp;" : picture_to_assign.name %>
  </div>
</div>

app/views/alchemy/admin/pictures/_tag_list.html.erb
<% p = params.dup %>
<% if Alchemy::Picture.tag_counts.any? %>
  <h2><%= _t("Filter by tag") %></h2>
  <%= js_filter_field '#tag_list li' %>
  <ul>
    <%= render_tag_list('Alchemy::Picture', p) %>
  </ul>
  <% if p[:tagged_with].present? %>
    <%= link_to(
      render_icon('delete-small') + _t('Remove tag filter'),
      url_for(p.delete_if { |k, v| k == "tagged_with" }.merge(action: 'index')),
      remote: request.xhr?,
      class: 'button small with_icon please_wait'
    ) %>
  <% end %>
<% end %>

app/views/alchemy/admin/pictures/archive_overlay.js.erb
(function() {
  var dialog = Alchemy.currentDialog();
  dialog.dialog_body.html('<%= j render("archive_overlay") %>');
  Alchemy.SelectBox('#filter_bar');
  Alchemy.watchForDialogs(dialog.dialog_body);
  Alchemy.ImageLoader('#assign_image_list');
  Alchemy.ListFilter(dialog.dialog_body);
})();

app/views/alchemy/admin/pictures/edit.html.erb
<%= alchemy_form_for [:admin, @picture] do |f| %>
  <%= hidden_field_tag :query, params[:query] %>
  <%= hidden_field_tag :size, params[:size] %>
  <%= hidden_field_tag :tagged_with, params[:tagged_with] %>
  <%= hidden_field_tag :filter, params[:filter] %>
  <%= f.input :name %>
  <div class="input tag_list">
    <%= f.label :tag_list %>
    <%= render 'alchemy/admin/partials/autocomplete_tag_list', f: f %>
    <small class="hint"><%= _t('Please seperate the tags with commata') %></small>
  </div>
  <%= f.submit _t(:save) %>
<% end %>

app/views/alchemy/admin/pictures/edit_multiple.html.erb
<%= form_tag update_multiple_admin_pictures_path do %>
  <%= hidden_field_tag :query, params[:query] %>
  <%= hidden_field_tag :size, params[:size] %>
  <%= hidden_field_tag :tagged_with, params[:tagged_with] %>
  <%= hidden_field_tag :filter, params[:filter] %>

  <% @pictures.pluck(:id).each do |id| %>
  <%= hidden_field_tag "picture_ids[]", id %>
  <% end %>

  <div class="info">
    <%= render_icon :info %>
    <p><%= _t('You are about to edit many pictures at once') % {length: @pictures.size} %></p>
  </div>

  <div class="input text">
    <%= label_tag :pictures_name, _t('Name'), class: 'control-label' %>
    <%= text_field_tag :pictures_name %>
  </div>

  <div class="input tag_list">
    <%= label_tag :pictures_tag_list, _t(:tags), class: 'control-label' %>
    <%= text_field_tag :pictures_tag_list, @tags, data: {autocomplete: alchemy.autocomplete_admin_tags_path} %>
    <small class="hint"><%= _t('Please seperate the tags with commata') %></small>
  </div>

  <div class="submit">
    <%= button_tag _t(:save), name: nil, class: 'button' %>
  </div>
<% end %>

app/views/alchemy/admin/pictures/flush.js.erb
Alchemy.growl('<%= @notice %>');
Alchemy.pleaseWaitOverlay(false);

app/views/alchemy/admin/pictures/index.html.erb
<% content_for(:toolbar) do %>
  <div class="toolbar_buttons">
    <%= toolbar_button(
      icon: 'upload',
      label: _t(:upload_image),
      url: alchemy.new_admin_picture_path(size: @size),
      hotkey: 'alt+n',
      dialog_options: {
        title: _t(:upload_image),
        size: '540x525'
      },
      class: 'icon_button',
      title: _t(:upload_image),
      if_permitted_to: [:create, Alchemy::Picture]
    ) %>
    <% if can? :create, Alchemy::Picture %>
    <div class="toolbar_spacer"></div>
    <% end %>
    <div class="button_group">
      <div class="button_with_label">
        <%= link_to(
          render_icon('zoom-out'),
          alchemy.admin_pictures_path({
            size: "small",
            query: params[:query]
          }),
          title: _t(:small_thumbnails),
          class: "icon_button please_wait"
        ) %>
      </div>
      <div class="button_with_label">
        <%= link_to(
          render_icon('zoom-equal'),
          alchemy.admin_pictures_path({
            size: "medium",
            query: params[:query]
          }),
          title: _t(:medium_thumbnails),
          class: "icon_button please_wait"
        ) %>
      </div>
      <div class="button_with_label">
        <%= link_to(
          render_icon('zoom-in'),
          alchemy.admin_pictures_path({
            size: "large",
            query: params[:query]
          }),
          title: _t(:big_thumbnails),
          class: "icon_button please_wait"
        ) %>
      </div>
      <label><%= _t('Image size') %></label>
      <%= hidden_field_tag('size', @size, id: 'overlay_thumbnails_size') %>
    </div>
    <% if can?(:flush, Alchemy::Picture) %>
      <div class="toolbar_spacer"></div>
      <%= toolbar_button(
        icon: 'flush',
        url: alchemy.flush_admin_pictures_path,
        dialog: false,
        link_options: {
          remote: true,
          method: :post
        },
        label: _t('Flush picture cache'),
        class: 'icon_button please_wait',
        title: _t('Flush picture cache'),
        skip_permission_check: true
      ) %>
    <% end %>
    <div class="toolbar_spacer"></div>
    <div class="button_with_label">
      <%= link_to(
        render_icon('select_all'),
        '',
        id: 'select_all_pictures',
        class: 'icon_button',
        'data-alchemy-hotkey' => 'alt+a'
      ) %>
      <label><%= _t("Select all") %></label>
    </div>
  </div>

  <%= render partial: 'alchemy/admin/partials/search_form' %>
<% end %>

<div id="picture_archive">
  <h1>
    <%= @pictures.total_count %>
    <%= Alchemy::Picture.model_name.human(count: @pictures.total_count) %>
    <%= _t("picture_library.filter.#{params[:filter]}") if params[:filter].present? %>
  </h1>
  <%= render 'archive' %>
</div>

<% content_for :javascripts do %>
  <script type="text/javascript" charset="utf-8">
    $(function() {
      Alchemy.pictureSelector();
      $('#select_all_pictures').on('click', function(e) {
        $('.picture_tool.select :checkbox').prop('checked', true).change();
        e.preventDefault;
        return false;
      });

    });
  </script>
<% end %>

app/views/alchemy/admin/pictures/index.js.erb
Alchemy.pleaseWaitOverlay(false);
$('#archive_all').html('<%= j render("archive") %>');
$('#filter_bar').replaceWith('<%= j render("filter_bar") %>');

app/views/alchemy/admin/pictures/info.html.erb
<div class="resource_info">
  <div class="value">
    <label><%= Alchemy::Picture.human_attribute_name :name %></label>
    <p><%= @picture.name %></p>
  </div>
  <div class="value">
    <label><%= Alchemy::Picture.human_attribute_name :image_file_name %></label>
    <p><%= @picture.image_file_name %></p>
  </div>
  <div class="value">
    <label><%= Alchemy::Picture.human_attribute_name :image_file_dimensions %></label>
    <p><%= @picture.image_file_dimensions %> px</p>
  </div>
  <div class="value">
    <label><%= Alchemy::Picture.human_attribute_name :image_file_size %></label>
    <p><%= number_to_human_size @picture.image_file_size %></p>
  </div>

  <% unless @picture.deletable? %>
    <h2><%= _t(:this_picture_is_used_on_these_pages) %>:</h2>
    <div id="pictures_page_list">
    <% @picture.essence_pictures.group_by(&:page).each do |page, essence_pictures| %>
      <div class="value">
        <label><%= link_to page.name, edit_admin_page_path(page) %></label>
        <ul>
          <% essence_pictures.group_by(&:element).each do |element, essence_pictures| %>
          <li class="<%= cycle('even', 'odd') %>">
            <%= link_to element.display_name_with_preview_text, edit_admin_page_path(page, :anchor => "element_#{element.id}") %> in
            <%= essence_pictures.collect { |e| e.content.name_for_label }.to_sentence %>
          </li>
          <% end %>
        </ul>
      </div>
    <% end %>
    </div>
  <% end %>
</div>

app/views/alchemy/admin/pictures/new.html.erb
<%= form_for [:admin, @picture], html: {multipart: true} do |f| %>
  <%= render 'alchemy/admin/partials/upload_form', {
      file_types: configuration(:uploader)['allowed_filetypes']['pictures'],
      file_types_description: _t(:images),
      redirect_url: admin_pictures_path(
        size: params[:size],
        filter: 'last_upload',
        element_id: @element ? @element.id : nil,
        content_id: @content ? @content.id : nil,
        options: @options ? @options.to_json : nil),
      model_name: 'picture',
      file_attribute: 'image_file',
      item_type: _t(:images)
    } %>
  <%= f.submit :upload, class: 'upload-button' %>
<% end %>